#!/usr/bin/env bash
set -euo pipefail
BASE=/opt/llm-server; RELEASES="${BASE}/releases"; STAGING="${BASE}/staging"; LOCK="${RELEASES}/deploy.lock"
SERVICES=(autonomy dashboard agent monitor router ollama llama-server)
dir(){ echo "${RELEASES}/$1"; }
verify(){ local d; d=$(dir "$1"); test -f "$d/application.tar.gz"; (cd "$d" && sha256sum -c SHA256SUMS); }
state(){ cat "$(dir "$1")/status" 2>/dev/null || true; }
deployment_event(){ local file=$1 state=$2 backup=${3:-}; printf '{"state":"%s","time":"%s","backup_id":"%s"}\n' "$state" "$(date -u +%FT%TZ)" "$backup" >> "$file"; }
baseline(){ local id=${1:?baseline id required} d previous; d=$(dir "$id"); test ! -e "$d"; previous=$(readlink -f "$RELEASES/current" 2>/dev/null || true); install -d -m 0750 "$d"; tar -C "$BASE" -czf "$d/application.tar.gz" apps services config deploy scripts docs; (cd "$d" && sha256sum application.tar.gz > SHA256SUMS); printf 'parent=\ncreated=%s\n' "$(date -u +%FT%TZ)" > "$d/manifest"; test -z "$previous" || echo SUPERSEDED > "$previous/status"; echo ACTIVE > "$d/status"; ln -sfn "$d" "$RELEASES/current"; reconcile; echo "$id"; }
stage(){ local id=$1 cur work; cur=$(readlink -f "${RELEASES}/current"); work="${STAGING}/${id}/workspace"; test -n "$cur" && test ! -e "$work"; install -d -m 0750 "$work"; tar -xzf "$cur/application.tar.gz" -C "$work"; printf 'parent=%s\ncreated=%s\n' "$(basename "$cur")" "$(date -u +%FT%TZ)" > "${STAGING}/${id}/manifest"; echo "$work"; }
candidate(){ local id=$1 w d; w="${STAGING}/${id}/workspace"; d=$(dir "$id"); test -d "$w" && test ! -e "$d"; install -d -m 0750 "$d"; tar -C "$w" -czf "$d/application.tar.gz" apps services config deploy scripts docs; (cd "$d" && sha256sum application.tar.gz > SHA256SUMS); cp "${STAGING}/${id}/manifest" "$d/manifest"; echo PENDING > "$d/status"; echo "$id"; }
approve(){ local id=$1 approver=${2:?approver required} reason=${3:?reason required} d checksum approval_id; d=$(dir "$id"); test "$(state "$id")" = PENDING; checksum=$(awk '{print $1}' "$d/SHA256SUMS"); approval_id="approval-$(date -u +%Y%m%dT%H%M%SZ)-$RANDOM"; printf '{"approval_id":"%s","candidate_id":"%s","checksum":"%s","approver":"%s","reason":"%s","timestamp":"%s","policy_artifact":"%s"}\n' "$approval_id" "$id" "$checksum" "$approver" "$reason" "$(date -u +%FT%TZ)" "${STAGING}/${id}/artifacts/policy.json" > "$d/approval.json"; echo APPROVED > "$d/status"; }
list(){ local d id status checksum manifest approval; for d in "$RELEASES"/*; do test -d "$d" && test ! -L "$d" && test -f "$d/status" || continue; id=$(basename "$d"); status=$(tr -d '\n' < "$d/status"); checksum=$(awk 'NR==1{print $1}' "$d/SHA256SUMS" 2>/dev/null || true); manifest=$(tr '\n' ';' < "$d/manifest" 2>/dev/null || true); approval=$(awk -F'"' '/approval_id/{print $4; exit}' "$d/approval.json" 2>/dev/null || true); printf '%s\t%s\t%s\t%s\t%s\n' "$id" "$status" "$checksum" "$manifest" "$approval"; done; }
reconcile(){ local active d id status parent; active=$(basename "$(readlink -f "$RELEASES/current")"); for d in "$RELEASES"/*; do test -d "$d" && test ! -L "$d" && test -f "$d/status" || continue; id=$(basename "$d"); status=$(state "$id"); parent=$(sed -n 's/^parent=//p' "$d/manifest"); if test "$status" = ACTIVE && test "$id" != "$active"; then echo SUPERSEDED > "$d/status"; elif { test "$status" = PENDING || test "$status" = APPROVED; } && test "$parent" != "$active"; then echo STALE > "$d/status"; fi; done; }
timeline(){ local record; for record in "$RELEASES"/deployments/*.json; do test -f "$record" && cat "$record"; done; }
restore(){ local id=$1 d; d=$(dir "$id"); tar -xzf "$d/application.tar.gz" -C "$BASE"; cp "$BASE"/config/systemd/*.service /etc/systemd/system/; systemctl daemon-reload; for s in ollama llama-server monitor router agent dashboard autonomy; do systemctl start "$s.service"; done; "$BASE/scripts/verify.sh"; ln -sfn "$d" "$RELEASES/current"; }
deploy(){ local id=$1 prev d deployment_id parent record backup; test "$(state "$id")" = APPROVED; test -f "$(dir "$id")/approval.json"; verify "$id"; flock -n 9 || { echo 'deploy lock busy' >&2; exit 1; }; prev=$(basename "$(readlink -f "$RELEASES/current")"); d=$(dir "$id"); parent=$(sed -n 's/^parent=//p' "$d/manifest"); test "$parent" = "$prev" || { echo "candidate parent $parent does not match active release $prev" >&2; exit 1; }; deployment_id="deploy-$(date -u +%Y%m%dT%H%M%SZ)-$RANDOM"; install -d -m 0750 "$RELEASES/deployments"; record="$RELEASES/deployments/${deployment_id}.json"; printf '{"deployment_id":"%s","candidate_id":"%s","parent_release":"%s","started":"%s"}\n' "$deployment_id" "$id" "$prev" "$(date -u +%FT%TZ)" > "$record"; deployment_event "$record" BACKUP_STARTED; if ! backup=$("$BASE/scripts/backup.sh"); then deployment_event "$record" BACKUP_FAILED; exit 1; fi; deployment_event "$record" BACKED_UP "${backup##*/}"; deployment_event "$record" APPLYING; for s in "${SERVICES[@]}"; do systemctl stop "$s.service" || true; done; if ! tar -xzf "$d/application.tar.gz" -C "$BASE" || ! cp "$BASE"/config/systemd/*.service /etc/systemd/system/ || ! systemctl daemon-reload || ! { for s in ollama llama-server monitor router agent dashboard autonomy; do systemctl start "$s.service"; done; } || ! "$BASE/scripts/verify.sh"; then deployment_event "$record" VERIFY_FAILED "${backup##*/}"; restore "$prev"; deployment_event "$record" ROLLED_BACK "${backup##*/}"; exit 1; fi; ln -sfn "$d" "$RELEASES/current"; echo DEPLOYED > "$d/status"; deployment_event "$record" SUCCESS "${backup##*/}"; }
install -d -m 0750 "$RELEASES" "$STAGING"
case "${1:-}" in baseline|create) baseline "$2";; stage) stage "$2";; candidate) candidate "$2";; approve) approve "$2" "$3" "$4";; list) list;; timeline) timeline;; reconcile) reconcile;; deploy) deploy "$2" 9>"$LOCK";; rollback) restore "$(basename "$(readlink -f "$RELEASES/current")")" 9>"$LOCK";; *) exit 2;; esac
