#!/usr/bin/env bash
set -euo pipefail
BASE=/opt/llm-server; RELEASES="${BASE}/releases"; STAGING="${BASE}/staging"; LOCK="${RELEASES}/deploy.lock"
SERVICES=(autonomy dashboard agent monitor router ollama llama-server)
dir(){ echo "${RELEASES}/$1"; }
verify(){ local d; d=$(dir "$1"); test -f "$d/application.tar.gz"; (cd "$d" && sha256sum -c SHA256SUMS); }
state(){ cat "$(dir "$1")/status" 2>/dev/null || true; }
stage(){ local id=$1 cur work; cur=$(readlink -f "${RELEASES}/current"); work="${STAGING}/${id}/workspace"; test -n "$cur" && test ! -e "$work"; install -d -m 0750 "$work"; tar -xzf "$cur/application.tar.gz" -C "$work"; printf 'parent=%s\ncreated=%s\n' "$(basename "$cur")" "$(date -u +%FT%TZ)" > "${STAGING}/${id}/manifest"; echo "$work"; }
candidate(){ local id=$1 w d; w="${STAGING}/${id}/workspace"; d=$(dir "$id"); test -d "$w" && test ! -e "$d"; install -d -m 0750 "$d"; tar -C "$w" -czf "$d/application.tar.gz" apps services config deploy scripts docs; (cd "$d" && sha256sum application.tar.gz > SHA256SUMS); cp "${STAGING}/${id}/manifest" "$d/manifest"; echo PENDING > "$d/status"; echo "$id"; }
approve(){ local id=$1 approver=${2:?approver required} reason=${3:?reason required} d checksum approval_id; d=$(dir "$id"); test "$(state "$id")" = PENDING; checksum=$(awk '{print $1}' "$d/SHA256SUMS"); approval_id="approval-$(date -u +%Y%m%dT%H%M%SZ)-$RANDOM"; printf '{"approval_id":"%s","candidate_id":"%s","checksum":"%s","approver":"%s","reason":"%s","timestamp":"%s","policy_artifact":"%s"}\n' "$approval_id" "$id" "$checksum" "$approver" "$reason" "$(date -u +%FT%TZ)" "${STAGING}/${id}/artifacts/policy.json" > "$d/approval.json"; echo APPROVED > "$d/status"; }
restore(){ local id=$1 d; d=$(dir "$id"); tar -xzf "$d/application.tar.gz" -C "$BASE"; cp "$BASE"/config/systemd/*.service /etc/systemd/system/; systemctl daemon-reload; for s in ollama llama-server monitor router agent dashboard autonomy; do systemctl start "$s.service"; done; "$BASE/scripts/verify.sh"; ln -sfn "$d" "$RELEASES/current"; }
deploy(){ local id=$1 prev d deployment_id; test "$(state "$id")" = APPROVED; test -f "$(dir "$id")/approval.json"; verify "$id"; flock -n 9 || { echo 'deploy lock busy' >&2; exit 1; }; prev=$(basename "$(readlink -f "$RELEASES/current")"); d=$(dir "$id"); deployment_id="deploy-$(date -u +%Y%m%dT%H%M%SZ)-$RANDOM"; install -d -m 0750 "$RELEASES/deployments"; printf '{"deployment_id":"%s","candidate_id":"%s","parent_release":"%s","started":"%s"}\n' "$deployment_id" "$id" "$prev" "$(date -u +%FT%TZ)" > "$RELEASES/deployments/${deployment_id}.json"; "$BASE/scripts/backup.sh"; for s in "${SERVICES[@]}"; do systemctl stop "$s.service" || true; done; if ! tar -xzf "$d/application.tar.gz" -C "$BASE" || ! cp "$BASE"/config/systemd/*.service /etc/systemd/system/ || ! systemctl daemon-reload || ! { for s in ollama llama-server monitor router agent dashboard autonomy; do systemctl start "$s.service"; done; } || ! "$BASE/scripts/verify.sh"; then restore "$prev"; printf '{"state":"ROLLED_BACK"}\n' >> "$RELEASES/deployments/${deployment_id}.json"; exit 1; fi; ln -sfn "$d" "$RELEASES/current"; echo DEPLOYED > "$d/status"; printf '{"state":"SUCCESS"}\n' >> "$RELEASES/deployments/${deployment_id}.json"; }
install -d -m 0750 "$RELEASES" "$STAGING"
case "${1:-}" in stage) stage "$2";; candidate) candidate "$2";; approve) approve "$2" "$3" "$4";; deploy) deploy "$2" 9>"$LOCK";; rollback) restore "$(basename "$(readlink -f "$RELEASES/current")")" 9>"$LOCK";; *) exit 2;; esac
